[package]
name = "hocuspocus-server"
version = "0.1.0"
edition = "2021"
description = "Axum WebSocket skeleton for hocuspocus-rs with fetch/store glue"
license = "MIT"

[features]
redis = ["hocuspocus-extension-redis"]

[dependencies]
anyhow = "1"
async-trait = "0.1"
axum = { version = "0.7", features = ["ws"] }
dashmap = "5"
futures-util = "0.3"
parking_lot = "0.12"
thiserror = "1"
tokio = { version = "1", features = [
  "macros",
  "rt-multi-thread",
  "sync",
  "time",
] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
yrs = "0.24"

hocuspocus-extension-database = { path = "../extension-database" }
hocuspocus-extension-sqlite = { path = "../extension-sqlite" }
hocuspocus-extension-redis = { path = "../extension-redis", optional = true }
