[package]
name = "hocuspocus-extension-database"
version = "0.1.0"
edition = "2021"
description = "Database persistence extension for hocuspocus-rs (MVP): trait and types"
license = "MIT"

[dependencies]
async-trait = "0.1"
anyhow = "1"
