name: CI

on:
  push:
    branches:
      - "**"
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test workspace (Rust 1.90)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust 1.90.0
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.90.0

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: .

      - name: Fetch dependencies
        run: cargo fetch --locked

      - name: Run tests (workspace)
        env:
          CARGO_TERM_COLOR: always
        run: cargo test --workspace --locked


